content/projects/_bldrs.md: rename from _blrds and fill in initial content.
opensource-construction/website pull request #142
Opened 2024-11-14 12:04 UTC by pablo-mayrgundter

Hi Max,

Here's our project page submission.

Thanks!
Pablo

2024-11-14 17:52 UTC, n0rdlicht requested changes
Hi @pablo-mayrgundter many thanks for submitting this. For the project to show up in the preview (just approved the preview build) you'll unfortunately need rename the file, see inline comment.

cc @MaximilianVomhof

2024-11-15 09:54 UTC, pablo-mayrgundter commented on content/projects/_bldrs.md
> +- [Bldrs Share GitHub](https://github.com/bldrs-ai/Share)
Tried just putting them all up top

2024-11-15 09:54 UTC, pablo-mayrgundter commented on content/projects/_bldrs.md
Done

2024-11-15 09:55 UTC, pablo-mayrgundter commented
PTAL

2024-11-15 10:10 UTC, n0rdlicht commented
nice - lgtm, looks good to me. @MaximilianVomhof please check https://opensource-construction-gs7jjvk0o-opensource-construction.vercel.app/projects/bldrs/ before we merge.

2024-11-15 10:11 UTC, n0rdlicht approved these changes

2024-11-16 13:57 UTC, merged